name: Gfwlist Decode

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch: # 支持手动触发

jobs:
  check-and-update:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出当前仓库
    - name: Checkout this repository
      uses: actions/checkout@v3

    # Step 2: 下载目标文件
    - name: Fetch target file from another repository
      run: |
        curl -o gfwlist64.txt https://raw.githubusercontent.com/gfwlist/gfwlist/refs/heads/master/gfwlist.txt

    # Step 3: 计算文件哈希值
    - name: Calculate file hash
      id: file_hash
      run: |
        # 计算目标文件的 SHA256 哈希
        sha256sum gfwlist64.txt | awk '{print $1}' > current_hash.txt

    # Step 4: 检查是否有更新
    - name: Compare hashes
      id: hash_check
      run: |
        # 如果 last_hash.txt 不存在，创建一个空文件
        if [ ! -f hash.txt ]; then
          touch hash.txt
        fi
        # 获取上次保存的哈希值
        LAST_HASH=$(cat hash.txt)
        # 获取当前文件的哈希值
        CURRENT_HASH=$(cat current_hash.txt)
        # 比较哈希值
        if [ "$LAST_HASH" = "$CURRENT_HASH" ]; then
          echo "no_update=true" >> $GITHUB_ENV
        else
          echo "no_update=false" >> $GITHUB_ENV
        fi

    # Step 5: 如果文件有更新，执行解码操作
    - name: Decode and Update
      if: env.no_update == 'false'
      run: |
        # 保存当前哈希值供下次比较
        mv current_hash.txt hash.txt
        # Base64 解码
        base64 -d gfwlist64.txt > gfwlist.txt
        # 提交更新到当前仓库
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add gfwlist.txt hash.txt
        git commit -m "Update decoded file: $(date)"
        git push origin HEAD
