name: Gfwlist Decode

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch: # 支持手动触发

jobs:
  check-and-update:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出当前仓库
    - name: Checkout this repository
      uses: actions/checkout@v3

    # Step 2: 下载目标文件
    - name: Fetch target file from another repository
      run: |
        curl -o gfwlist64.txt https://raw.githubusercontent.com/gfwlist/gfwlist/refs/heads/master/gfwlist.txt

    # Step 3: 计算文件哈希值
    - name: Calculate file hash
      id: file_hash
      run: |
        mkdir -p gfwlist
        sha256sum gfwlist64.txt | awk '{print $1}' > gfwlist/new_hash.txt

    # Step 4: 检查是否有更新
    - name: Compare hashes
      id: hash_check
      run: |
        mkdir -p gfwlist
        if [ ! -f gfwlist/hash.txt ]; then
          touch gfwlist/hash.txt
        fi
        LAST_HASH=$(cat gfwlist/hash.txt)
        CURRENT_HASH=$(cat gfwlist/new_hash.txt)
        if [ "$LAST_HASH" = "$CURRENT_HASH" ]; then
          echo "no_update=true" >> $GITHUB_ENV
        else
          echo "no_update=false" >> $GITHUB_ENV
        fi

    # Step 5: 如果文件有更新，执行解码操作
    - name: Decode and Update
      if: env.no_update == 'false'
      run: |
        mv gfwlist/new_hash.txt gfwlist/hash.txt
        base64 -d gfwlist64.txt > gfwlist/gfwlist.txt
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add gfwlist/gfwlist.txt gfwlist/hash.txt
        git commit -m "Update decoded file: $(date)"
        git push origin HEAD